-- Collection of Unicode icons for the application
-- Organized by category for easy reference

local icons = {
  -- Recording and playback
  transport = {
    record = "⏺",
    play = "▶",
    pause = "⏸",
    stop = "⏹",
    loop = "⟳",
    metronome = "⏱",
    shuffle = "⥮",
    repeat_one = "↺",
    repeat_all = "↻",
  },
  
  -- Lain
  lain = {
    network = "⌬",        
    protocol = "⎆",       
    layer = "⌗",         
    wire = "⌇",         
    node = "◉",         
    terminal = "⌸",
    presence = "⚈",
    absence = "⚆",
    boundary = "⌯",
    gateway = "⎊",
    signal = "⌁",
    noise = "⌿",
    void = "∅",
    connection = "⌇",
    consciousness = "◎",
    memory = "⎔",
    dream = "⌖",
    reality = "⌺",
    interface = "⌘",
    pulse = "⌁",
    static = "⌇",
    echo = "◌",
    recursion = "∞",
    threshold = "⌅",
    emergence = "◬",
    dissolution = "◈",
    pattern = "⌘",
    nexus = "⎈",
    cipher = "⌗",
    manifold = "⎍",
  },
  
  -- Music and sound
  music = {
    note = "♪",
    notes = "♫",
    treble_clef = "𝄞",
    bass_clef = "𝄢",
    microphone = "⏲",
    wave = "〰",
    pulse = "⌁",
    eighth_note = "♪",
    beamed_notes = "♫",
    flat = "♭",
    sharp = "♯",
    natural = "♮",
    fermata = "𝄐",
  },
  
  -- Time and cycles
  time = {
    infinity = "∞",
    sun = "☀",
    moon = "☽",
    star = "✧",
    sparkles = "✦",
    phases = "◑",
    cycle = "↻",
    quantum = "⌬",
    timeline = "⎯",
    portal = "◎",
  },
  
  -- Status and State
  status = {
    active = "◉",
    inactive = "◯",
    warning = "⚠",
    error = "⚡",
    success = "✓",
    pending = "↺",
    locked = "⚿",
    unlocked = "⚷",
    connected = "⌘",
    disconnected = "⌀",
    synced = "⟲",
    processing = "⚙",
  },
  
  -- Mystical and poetic
  mystical = {
    crystal = "◈",
    spiral = "§",
    flower = "❀",
    lotus = "⚘",
    eye = "◉",
    cosmos = "✧",
    alchemy = "⚗",
    eternity = "֍",
    eternity_left = "֎",
    om = "ॐ",
    wheel = "☸",
    yin_yang = "☯",
    comet = "☄",
    peace = "☮",
    ankh = "☥",
    chi_rho = "☧",
    cross_orthodox = "☦",
    star_david = "✡",
    dharma = "☸",
    meditation = "⎈",
    flame = "△",
    svasti = "࿕",
    svasti_dots = "࿗",
    merkaba = "✡",
    tree_of_life = "⎋",
    ouroboros = "⟲",
    third_eye = "◉",
    void = "∅",
    unity = "☯",
  },
  
  -- Electricity and energy
  electricity = {
    lightning = "⚡",
    electric_arrow = "⌁",
    spark = "⚊",
    current = "⎓",
    ac = "⏦",
    ground = "⏚",
    power = "⏻",
    power_on = "⏽",
    power_off = "⭘",
    energy = "⚛",
    resistance = "⏲",
    voltage = "⚍",
    wave = "⌇",
    frequency = "≋",
    resonance = "◌",
    pulse_wave = "⎍",
    sine_wave = "∿",
  },
  
  -- Sacred Geometry
  sacred_geometry = {
    circle = "○",
    dot = "•",
    square = "□",
    triangle = "△",
    hexagon = "⬡",
    pentagon = "⬠",
    octagon = "⯃",
    vesica_piscis = "◉",
    seed_of_life = "⌘",
    flower_of_life = "✾",
    metatron = "✴",
    golden_ratio = "φ",
  },
  
  -- Quantum and Digital
  quantum = {
    superposition = "⨁",
    entanglement = "⟗",
    wave_particle = "⥊",
    probability = "⚄",
    matrix = "⧉",
    qubit = "⟲",
    uncertainty = "≎",
    collapse = "⧊",
    digital_rain = "⋮",
    binary = "⚍",
    quantum_gate = "  ",
    quantum_gate_open = "⊟",
  },
  
  -- UI elements
  ui = {
    dot = "•",
    diamond = "◇",
    square = "□",
    circle = "○",
    arrow_right = "→",
    arrow_left = "←",
    arrow_up = "↑",
    arrow_down = "↓",
    check = "✓",
    cross = "✕",
    menu = "☰",
    settings = "⚙",
    search = "⚲",
    link = "⛓",
    external_link = "↗",
    maximize = "⤢",
    minimize = "⤫",
    close = "✕",
  },
}

return icons 